#!/usr/bin/python3
# SPDX-FileCopyrightText: 2023 Tatsuki Yanagisawa
# SPDX-License-Identifier: GPL-3.0
import sys

ans = 0.0
for line in sys.stdin:
    try:
        ans += int(line)
    except:
        ans += float(line)

print(ans)

